language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jeremyschneider/docker-react -f Dockerfile.dev .

script:
    - docker run jeremyschneider/docker-react npm run test -- --coverage