language: generic
services:
    - docker

before_install:
    - docker build -t jeremyschneider/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jeremyschneider/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-bis"
    env: "DockerReactBis-env"
    bucket_name: "elasticbeanstalk-us-east-2-949849276001"
    bucket_path: "docker-react-bis"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
