language: generic
services:
    - docker

before_install:
    - docker build -t jeremyschneider/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jeremyschneider/docker-react npm run test -- --coverage